//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmox.WebGUI.Forms.CompanionKit.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmox.WebGUI.Forms.CompanionKit.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string CannotBePreviewed {
            get {
                return ResourceManager.GetString("CannotBePreviewed", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string gss {
            get {
                return ResourceManager.GetString("gss", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string SEOItemResourceTemplate {
            get {
                return ResourceManager.GetString("SEOItemResourceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string SEOItemTemplate {
            get {
                return ResourceManager.GetString("SEOItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string UserControlCSDesignerTemplate {
            get {
                return ResourceManager.GetString("UserControlCSDesignerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string UserControlCSTemplate {
            get {
                return ResourceManager.GetString("UserControlCSTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string UserControlResxTemplate {
            get {
                return ResourceManager.GetString("UserControlResxTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string UserControlVBDesignerTemplate {
            get {
                return ResourceManager.GetString("UserControlVBDesignerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        /// </summary>
        internal static string UserControlVBTemplate {
            get {
                return ResourceManager.GetString("UserControlVBTemplate", resourceCulture);
            }
        }
    }
}
