// Decompiled with JetBrains decompiler
// Type: Gizmox.WebGUI.Forms.ToolStripDropDown
// Assembly: Gizmox.WebGUI.Forms, Version=4.5.25701.0, Culture=neutral, PublicKeyToken=c508b41386c60f1d
// MVID: D9031956-0D2D-4DB7-BDA0-E996D0722B6C
// Assembly location: C:\Program Files (x86)\Gizmox\Visual WebGUI\SDK 4.5.2\Assemblies\Gizmox.WebGUI.Forms.dll
// XML documentation location: C:\Program Files (x86)\Gizmox\Visual WebGUI\SDK 4.5.2\Assemblies\Gizmox.WebGUI.Forms.xml

using Gizmox.WebGUI.Common.Extensibility;
using Gizmox.WebGUI.Common.Interfaces;
using Gizmox.WebGUI.Forms.Layout;
using Gizmox.WebGUI.Forms.Skins;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Globalization;
using System.Runtime.InteropServices;

namespace Gizmox.WebGUI.Forms
{
  /// <summary>
  /// 	<summary>Represents a control that allows the user to select a single item from a list that is displayed when the user clicks a <see cref="T:System.Windows.Forms.ToolStripDropDownButton"></see>. Although <see cref="T:System.Windows.Forms.ToolStripDropDownMenu"></see> and <see cref="T:System.Windows.Forms.ToolStripDropDown"></see> replace and add functionality to the <see cref="T:System.Windows.Forms.Menu"></see> control of previous versions, <see cref="T:System.Windows.Forms.Menu"></see> is retained for both backward compatibility and future use if you choose.</summary>
  /// </summary>
  [ComVisible(true)]
  [ClassInterface(ClassInterfaceType.AutoDispatch)]
  [ToolboxItem(false)]
  [Gizmox.WebGUI.Forms.Skins.Skin(typeof (ToolStripDropDownSkin))]
  [ClientController("Gizmox.WebGUI.Client.Controllers.ToolStripDropDownController, Gizmox.WebGUI.Client, Version=4.5.25701.0, Culture=neutral, PublicKeyToken=0fb8f99bd6cd7e23")]
  [Serializable]
  public class ToolStripDropDown : ToolStrip
  {
    private static readonly SerializableProperty mblnAutoCloseProperty = SerializableProperty.Register(nameof (mblnAutoClose), typeof (bool), typeof (ToolStripDropDown));
    private static readonly SerializableProperty mblnAutoSizeProperty = SerializableProperty.Register(nameof (mblnAutoSize), typeof (bool), typeof (ToolStripDropDown));
    private static readonly SerializableProperty mblnIsAutoGeneratedProperty = SerializableProperty.Register(nameof (mblnIsAutoGenerated), typeof (bool), typeof (ToolStripDropDown));
    private static readonly SerializableProperty mobjOwnerItemProperty = SerializableProperty.Register(nameof (mobjOwnerItem), typeof (ToolStripItem), typeof (ToolStripDropDown));
    private static readonly SerializableProperty menmCloseReasonProperty = SerializableProperty.Register(nameof (menmCloseReason), typeof (ToolStripDropDownCloseReason), typeof (ToolStripDropDown));
    private static readonly SerializableProperty mobjSourceComponentProperty = SerializableProperty.Register(nameof (mobjSourceComponent), typeof (Component), typeof (ToolStripDropDown));
    private static readonly SerializableProperty mobjSourceMemberComponentProperty = SerializableProperty.Register(nameof (mobjSourceMemberComponent), typeof (IIdentifiedComponent), typeof (ToolStripDropDown));
    private static readonly SerializableProperty mobjToolStripDropDownFormProperty = SerializableProperty.Register(nameof (mobjToolStripDropDownForm), typeof (ToolStripDropDown.ToolStripDropDownForm), typeof (ToolStripDropDown));
    private static readonly SerializableProperty HeaderPanelProperty = SerializableProperty.Register(nameof (HeaderPanel), typeof (ToolStripDropDown.ToolStripDropDownHeaderPanel), typeof (ToolStripDropDown), new SerializablePropertyMetadata((object) null));
    private static readonly SerializableEvent ClosedEvent = SerializableEvent.Register("Closed", typeof (ToolStripDropDownClosedEventHandler), typeof (ToolStripDropDown));
    private static readonly SerializableEvent OpenedEvent = SerializableEvent.Register("Opened", typeof (EventHandler), typeof (ToolStripDropDown));
    private static readonly SerializableEvent OpeningEvent = SerializableEvent.Register("Opening", typeof (CancelEventHandler), typeof (ToolStripDropDown));

    /// <summary>
    /// Initializes a new instance of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> class.
    /// </summary>
    public ToolStripDropDown()
    {
      this.mblnAutoClose = true;
      this.mblnAutoSize = true;
      this.SuspendLayout();
      this.Initialize();
      this.ResumeLayout(false);
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown" /> class.
    /// </summary>
    /// <param name="objOwnerItem">The owner item.</param>
    internal ToolStripDropDown(ToolStripItem objOwnerItem)
      : this()
    {
      this.mobjOwnerItem = objOwnerItem;
      if (objOwnerItem == null)
        return;
      ToolStrip parent = objOwnerItem.Parent;
      if (parent == null)
        return;
      this.ImageScalingSize = parent.ImageScalingSize;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown" /> class.
    /// </summary>
    /// <param name="objOwnerItem">The owner item.</param>
    /// <param name="blnIsAutoGenerated">if set to <c>true</c> [is auto generated].</param>
    internal ToolStripDropDown(ToolStripItem objOwnerItem, bool blnIsAutoGenerated)
      : this(objOwnerItem)
    {
      this.mblnIsAutoGenerated = blnIsAutoGenerated;
    }

    /// <summary>Sets the auto generated internal.</summary>
    /// <param name="autoGenerated">if set to <c>true</c> [auto generated].</param>
    internal void SetAutoGeneratedInternal(bool autoGenerated) => this.mblnIsAutoGenerated = autoGenerated;

    /// <summary>Initializes this instance.</summary>
    internal virtual void Initialize()
    {
      this.SetTopLevelInternal(true);
      this.SetStyle(ControlStyles.ResizeRedraw, true);
      this.GripStyle = ToolStripGripStyle.Hidden;
      this.LayoutStyle = ToolStripLayoutStyle.Flow;
      this.AutoSize = true;
    }

    /// <summary>Sets the close reason.</summary>
    /// <param name="reason">The reason.</param>
    internal void SetCloseReason(ToolStripDropDownCloseReason enmCloseReason) => this.menmCloseReason = enmCloseReason;

    /// <summary>
    /// Closes the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control.
    /// </summary>
    public void Close() => this.Close(ToolStripDropDownCloseReason.CloseCalled);

    /// <summary>
    /// Closes the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control for the specified reason.
    /// </summary>
    /// <param name="enmReason">One of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDownCloseReason"></see> values.</param>
    public void Close(ToolStripDropDownCloseReason enmReason)
    {
      this.SetCloseReason(enmReason);
      this.mobjToolStripDropDownForm.Close();
    }

    /// <summary>
    /// Raises the <see cref="E:Gizmox.WebGUI.Forms.ToolStripDropDown.Closed"></see> event.
    /// </summary>
    /// <param name="e">A <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDownClosedEventArgs"></see> that contains the event data.</param>
    protected virtual void OnClosed(ToolStripDropDownClosedEventArgs e)
    {
      ToolStripDropDownClosedEventHandler closedHandler = this.ClosedHandler;
      if (closedHandler == null)
        return;
      closedHandler((object) this, e);
    }

    /// <summary>Raises the <see cref="E:Gizmox.WebGUI.Forms.ToolStripDropDown.Closing"></see> event.</summary>
    /// <param name="e">A <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDownClosingEventArgs"></see> that contains the event data.</param>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    protected virtual void OnClosing(ToolStripDropDownClosingEventArgs e)
    {
    }

    /// <summary>
    /// Raises the <see cref="E:Gizmox.WebGUI.Forms.ToolStripDropDown.Opened"></see> event.
    /// </summary>
    /// <param name="e">An <see cref="T:System.EventArgs"></see> that contains the event data.</param>
    protected virtual void OnOpened(EventArgs e)
    {
      EventHandler openedHandler = this.OpenedHandler;
      if (openedHandler == null)
        return;
      openedHandler((object) this, e);
    }

    /// <summary>
    /// Raises the <see cref="E:Gizmox.WebGUI.Forms.ToolStripDropDown.Opening"></see> event.
    /// </summary>
    /// <param name="e">A <see cref="T:System.ComponentModel.CancelEventArgs"></see> that contains the event data.</param>
    protected virtual void OnOpening(CancelEventArgs e)
    {
      CancelEventHandler openingHandler = this.OpeningHandler;
      if (openingHandler == null)
        return;
      openingHandler((object) this, e);
    }

    /// <summary>
    /// Displays the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control in its default position.
    /// </summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new void Show() => this.ShowCore(ToolStripDropDownDirection.Default);

    /// <summary>Shows the specified control.</summary>
    /// <param name="objComponent">The control.</param>
    /// <param name="objPosition">The position.</param>
    public void Show(Component objComponent, Point objPosition) => this.Show(objComponent, objPosition, ToolStripDropDownDirection.Default);

    /// <summary>Shows the core.</summary>
    /// <param name="objDirection">The direction.</param>
    private void ShowCore(ToolStripDropDownDirection objDirection)
    {
      if (this.SourceComponentInternal == null && this.OwnerItem == null)
        this.SourceComponentInternal = (Component) (VWGContext.Current.MainForm as Form);
      DialogAlignment enmAlignment = DialogAlignment.Custom;
      CancelEventArgs e = new CancelEventArgs(this.Items.Count == 0);
      this.OnOpening(e);
      if (e.Cancel || this.Items.Count <= 0)
        return;
      this.mobjToolStripDropDownForm = this.CreateToolStripDropDownForm();
      if (this.mobjToolStripDropDownForm == null)
        return;
      switch (objDirection)
      {
        case ToolStripDropDownDirection.AboveLeft:
        case ToolStripDropDownDirection.AboveRight:
          enmAlignment = DialogAlignment.Above;
          break;
        case ToolStripDropDownDirection.BelowLeft:
        case ToolStripDropDownDirection.BelowRight:
          enmAlignment = DialogAlignment.Below;
          break;
        case ToolStripDropDownDirection.Left:
          enmAlignment = DialogAlignment.Left;
          break;
        case ToolStripDropDownDirection.Right:
          enmAlignment = DialogAlignment.Right;
          break;
      }
      Component componentInternal = this.SourceComponentInternal;
      if (componentInternal != null)
      {
        this.mobjToolStripDropDownForm.Location = this.Location;
        int num = (int) this.mobjToolStripDropDownForm.ShowPopup(componentInternal, this.SourceMemberComponentInternal, enmAlignment);
      }
      else
      {
        ToolStripItem ownerItem = this.OwnerItem;
        if (ownerItem == null)
          return;
        ToolStrip owner = ownerItem.Owner;
        if (owner == null)
          return;
        if (owner is ToolStripDropDown toolStripDropDown)
        {
          Form dropDownForm = toolStripDropDown.DropDownForm;
          if (dropDownForm == null || !dropDownForm.Visible)
          {
            int num1 = (int) this.mobjToolStripDropDownForm.ShowPopup(this.Context.ActiveForm as Form);
          }
          else
          {
            int num2 = (int) this.mobjToolStripDropDownForm.ShowPopup(dropDownForm, (IRegisteredComponentMember) ownerItem, this.Context.RightToLeft ? DialogAlignment.Left : DialogAlignment.Right);
          }
        }
        else
        {
          if (!(owner.TopLevelControl is Form topLevelControl))
            return;
          int num = (int) this.mobjToolStripDropDownForm.ShowPopup(topLevelControl, (IRegisteredComponentMember) ownerItem, DialogAlignment.Below);
        }
      }
    }

    /// <summary>Creates the tool strip drop down form.</summary>
    /// <returns></returns>
    private ToolStripDropDown.ToolStripDropDownForm CreateToolStripDropDownForm()
    {
      ToolStripDropDown.ToolStripDropDownForm downFormInstance = this.CreateToolStripDropDownFormInstance();
      downFormInstance.StartPosition = FormStartPosition.Manual;
      if (this.ClosedHandler != null)
        downFormInstance.Closed += new EventHandler(this.OnToolStripDropDownFormClosed);
      if (this.OpenedHandler != null)
        downFormInstance.Load += new EventHandler(this.OnToolStripDropDownFormLoaded);
      return downFormInstance;
    }

    /// <summary>Creates the tool strip drop down form instance.</summary>
    /// <returns></returns>
    protected virtual ToolStripDropDown.ToolStripDropDownForm CreateToolStripDropDownFormInstance() => new ToolStripDropDown.ToolStripDropDownForm(this);

    /// <summary>Called when [tool strip drop down form loaded].</summary>
    /// <param name="sender">The sender.</param>
    /// <param name="e">The <see cref="T:System.EventArgs" /> instance containing the event data.</param>
    private void OnToolStripDropDownFormLoaded(object sender, EventArgs e) => this.OnOpened(EventArgs.Empty);

    /// <summary>
    /// Handles the Closed event of the objToolStripDropDownForm control.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">The <see cref="T:System.EventArgs" /> instance containing the event data.</param>
    private void OnToolStripDropDownFormClosed(object sender, EventArgs e) => this.OnClosed(new ToolStripDropDownClosedEventArgs(ToolStripDropDownCloseReason.AppFocusChange));

    /// <summary>Shows the specified control.</summary>
    /// <param name="objControl">The control.</param>
    /// <param name="objPosition">The position.</param>
    /// <param name="enmDirection">The direction.</param>
    public void Show(
      Component objComponent,
      Point objPosition,
      ToolStripDropDownDirection enmDirection)
    {
      this.SourceComponentInternal = objComponent != null ? objComponent : throw new ArgumentNullException(nameof (objComponent));
      this.SourceMemberComponentInternal = (IIdentifiedComponent) null;
      this.Show(objPosition, enmDirection);
    }

    /// <summary>Shows the specified control.</summary>
    /// <param name="objControl">The control.</param>
    /// <param name="objMemberComponent">The member component.</param>
    /// <param name="objPoint">The point.</param>
    public void Show(
      Component objComponent,
      IIdentifiedComponent objMemberComponent,
      Point objPoint)
    {
      this.SourceComponentInternal = objComponent != null ? objComponent : throw new ArgumentNullException(nameof (objComponent));
      this.SourceMemberComponentInternal = objMemberComponent;
      this.Show(objPoint);
    }

    /// <summary>Shows the specified control.</summary>
    /// <param name="objControl">The control.</param>
    /// <param name="intX">The X.</param>
    /// <param name="intY">The Y.</param>
    public void Show(Control objControl, int intX, int intY) => this.Show((Component) objControl, new Point(intX, intY));

    /// <summary>Shows the drop down.</summary>
    /// <param name="objComponent">The component.</param>
    /// <param name="intX">The X.</param>
    /// <param name="intY">The Y.</param>
    internal void ShowDropDown(Component objComponent, int intX, int intY)
    {
      this.SourceComponentInternal = objComponent != null ? objComponent : throw new ArgumentNullException(nameof (objComponent));
      this.SourceMemberComponentInternal = (IIdentifiedComponent) null;
      this.Show(new Point(intX, intY));
    }

    /// <summary>Shows the drop down.</summary>
    /// <param name="objOwnerItem">The obj owner item.</param>
    internal void ShowDropDown(ToolStripDropDownItem objOwnerItem)
    {
      this.OwnerItem = (ToolStripItem) objOwnerItem;
      this.SourceComponentInternal = (Component) null;
      this.Location = Point.Empty;
      this.ShowCore(ToolStripDropDownDirection.Default);
    }

    /// <summary>Positions the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> relative to the specified screen location.</summary>
    /// <param name="screenLocation">The horizontal and vertical location of the screen's upper-left corner, in pixels.</param>
    /// <filterpriority>1</filterpriority>
    /// <PermissionSet>
    ///   <IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    ///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    ///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    ///   <IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    public void Show(Point screenLocation) => this.Show(screenLocation, ToolStripDropDownDirection.Default);

    /// <summary>Positions the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> relative to the specified control location and with the specified direction relative to the parent control.</summary>
    /// <param name="direction">One of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDownDirection"></see> values.</param>
    /// <param name="position">The horizontal and vertical location of the reference control's upper-left corner, in pixels.</param>
    public void Show(Point position, ToolStripDropDownDirection direction)
    {
      this.Location = position;
      this.ShowCore(direction);
    }

    /// <summary>Positions the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> relative to the specified screen coordinates.</summary>
    /// <param name="y">The vertical screen coordinate, in pixels.</param>
    /// <param name="x">The horizontal screen coordinate, in pixels.</param>
    /// <filterpriority>1</filterpriority>
    /// <PermissionSet>
    ///   <IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    ///   <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    ///   <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    ///   <IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    public void Show(int x, int y) => this.Show(new Point(x, y));

    /// <summary>Sets the control to the specified visible state.</summary>
    /// <param name="blnValue">true to make the control visible; otherwise, false.</param>
    protected override void SetVisibleCore(bool blnValue)
    {
      if (blnValue || !this.AutoClose || this.mobjToolStripDropDownForm == null)
        return;
      this.mobjToolStripDropDownForm.Close();
    }

    /// <summary>
    /// Raises the <see cref="E:System.Windows.Forms.ToolStrip.ItemAdded"></see> event.
    /// </summary>
    /// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemEventArgs"></see> that contains the event data.</param>
    protected internal override void OnItemAdded(ToolStripItemEventArgs e)
    {
      base.OnItemAdded(e);
      if (this.mobjOwnerItem == null)
        return;
      this.mobjOwnerItem.UpdateParams(AttributeType.Extended);
    }

    /// <summary>
    /// Raises the <see cref="E:System.Windows.Forms.ToolStrip.ItemRemoved"></see> event.
    /// </summary>
    /// <param name="e">A <see cref="T:System.Windows.Forms.ToolStripItemEventArgs"></see> that contains the event data.</param>
    protected internal override void OnItemRemoved(ToolStripItemEventArgs e)
    {
      base.OnItemRemoved(e);
      if (this.mobjOwnerItem == null)
        return;
      this.mobjOwnerItem.UpdateParams(AttributeType.Extended);
    }

    /// <summary>Occurs when the value of the <see cref="P:Gizmox.WebGUI.Forms.Control.BackgroundImage"></see> property changes.</summary>
    [Browsable(false)]
    public new event EventHandler BackgroundImageChanged
    {
      add => base.BackgroundImageChanged += value;
      remove => base.BackgroundImageChanged -= value;
    }

    /// <summary>Occurs when the value of the <see cref="P:Gizmox.WebGUI.Forms.Control.BackgroundImage"></see> property changes.</summary>
    [Browsable(false)]
    public new event EventHandler BackgroundImageLayoutChanged
    {
      add => base.BackgroundImageLayoutChanged += value;
      remove => base.BackgroundImageLayoutChanged -= value;
    }

    /// <summary>Occurs when the value of the <see cref="P:Gizmox.WebGUI.Forms.ToolStrip.BindingContext"></see> property changes.</summary>
    [Browsable(false)]
    public new event EventHandler BindingContextChanged
    {
      add => base.BindingContextChanged += value;
      remove => base.BindingContextChanged -= value;
    }

    /// <summary>Occurs when the focus or keyboard user interface (UI) cues change.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event UICuesEventHandler ChangeUICues;

    /// <summary>Occurs when the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is closed.</summary>
    /// <filterpriority>1</filterpriority>
    public event ToolStripDropDownClosedEventHandler Closed
    {
      add => this.AddHandler(ToolStripDropDown.ClosedEvent, (Delegate) value);
      remove => this.RemoveHandler(ToolStripDropDown.ClosedEvent, (Delegate) value);
    }

    /// <summary>Gets the closed handler.</summary>
    /// <value>The closed handler.</value>
    private ToolStripDropDownClosedEventHandler ClosedHandler => (ToolStripDropDownClosedEventHandler) this.GetHandler(ToolStripDropDown.ClosedEvent);

    /// <summary>Occurs when the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control is about to close.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event ToolStripDropDownClosingEventHandler Closing;

    /// <summary>This event is not relevant to this class.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler ContextMenuChanged;

    /// <summary>This event is not relevant to this class.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event EventHandler ContextMenuStripChanged
    {
      add => base.ContextMenuStripChanged += value;
      remove => base.ContextMenuStripChanged -= value;
    }

    /// <summary>This event is not relevant to this class.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler DockChanged;

    /// <summary>Occurs when the focus enters the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see>.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event EventHandler Enter
    {
      add => base.Enter += value;
      remove => base.Enter -= value;
    }

    /// <summary>Occurs when the value of the <see cref="P:Gizmox.WebGUI.Forms.ToolStripDropDown.Font"></see> property changes.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event EventHandler FontChanged
    {
      add => base.FontChanged += value;
      remove => base.FontChanged -= value;
    }

    /// <summary>Occurs when the value of the <see cref="P:Gizmox.WebGUI.Forms.ToolStrip.ForeColor"></see> property changes.</summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    public new event EventHandler ForeColorChanged
    {
      add => base.ForeColorChanged += value;
      remove => base.ForeColorChanged -= value;
    }

    /// <summary>This event is not relevant for this class.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event GiveFeedbackEventHandler GiveFeedback;

    /// <summary>Occurs when the user requests help for a control.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public new event HelpEventHandler HelpRequested;

    /// <summary>Occurs when the <see cref="E:Gizmox.WebGUI.Forms.ToolStripDropDown.ImeModeChanged"></see> property has changed.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler ImeModeChanged;

    /// <summary>Occurs when a key is pressed and held down while the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> has focus.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event KeyEventHandler KeyDown
    {
      add => base.KeyDown += value;
      remove => base.KeyDown -= value;
    }

    /// <summary>Occurs when a key is pressed while the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> has focus.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event KeyPressEventHandler KeyPress
    {
      add => base.KeyPress += value;
      remove => base.KeyPress -= value;
    }

    /// <summary>Occurs when a key is released while the control has focus.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event KeyEventHandler KeyUp
    {
      add => base.KeyUp += value;
      remove => base.KeyUp -= value;
    }

    /// <summary>Occurs when the input focus leaves the control.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    public new event EventHandler Leave
    {
      add => base.Leave += value;
      remove => base.Leave -= value;
    }

    /// <summary>
    /// Occurs when the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is opened.
    /// </summary>
    public event EventHandler Opened
    {
      add => this.AddHandler(ToolStripDropDown.OpenedEvent, (Delegate) value);
      remove => this.RemoveHandler(ToolStripDropDown.OpenedEvent, (Delegate) value);
    }

    /// <summary>Gets the opened handler.</summary>
    /// <value>The opened handler.</value>
    private EventHandler OpenedHandler => (EventHandler) this.GetHandler(ToolStripDropDown.OpenedEvent);

    /// <summary>Occurs when the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control is opening.</summary>
    [SRCategory("CatAction")]
    [SRDescription("ToolStripDropDownOpeningDescr")]
    public event CancelEventHandler Opening
    {
      add => this.AddHandler(ToolStripDropDown.OpeningEvent, (Delegate) value);
      remove => this.RemoveHandler(ToolStripDropDown.OpeningEvent, (Delegate) value);
    }

    /// <summary>Gets the opening handler.</summary>
    /// <value>The opening handler.</value>
    private CancelEventHandler OpeningHandler => (CancelEventHandler) this.GetHandler(ToolStripDropDown.OpeningEvent);

    /// <summary>Occurs when the value of the <see cref="P:Gizmox.WebGUI.Forms.ToolStripDropDown.Region"></see> property changes.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler RegionChanged;

    /// <summary>This event is not relevant for this class.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event ScrollEventHandler Scroll;

    /// <summary>Occurs when the <see cref="T:Gizmox.WebGUI.Forms.ToolStripLayoutStyle"></see> style changes.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler StyleChanged;

    /// <summary>This event is not relevant to this class.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler TabIndexChanged;

    /// <summary>This event is not relevant for this class.</summary>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public event EventHandler TabStopChanged;

    /// <summary>This event is not relevant for this class.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new event EventHandler TextChanged
    {
      add => base.TextChanged += value;
      remove => base.TextChanged -= value;
    }

    /// <summary>This event is not relevant for this class.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new event EventHandler Validated
    {
      add => base.Validated += value;
      remove => base.Validated -= value;
    }

    /// <summary>This event is not relevant for this class.</summary>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new event CancelEventHandler Validating
    {
      add => base.Validating += value;
      remove => base.Validating -= value;
    }

    private bool mblnAutoClose
    {
      get => this.GetValue<bool>(ToolStripDropDown.mblnAutoCloseProperty);
      set => this.SetValue<bool>(ToolStripDropDown.mblnAutoCloseProperty, value);
    }

    private bool mblnAutoSize
    {
      get => this.GetValue<bool>(ToolStripDropDown.mblnAutoSizeProperty);
      set => this.SetValue<bool>(ToolStripDropDown.mblnAutoSizeProperty, value);
    }

    private bool mblnIsAutoGenerated
    {
      get => this.GetValue<bool>(ToolStripDropDown.mblnIsAutoGeneratedProperty);
      set => this.SetValue<bool>(ToolStripDropDown.mblnIsAutoGeneratedProperty, value);
    }

    private ToolStripItem mobjOwnerItem
    {
      get => this.GetValue<ToolStripItem>(ToolStripDropDown.mobjOwnerItemProperty);
      set => this.SetValue<ToolStripItem>(ToolStripDropDown.mobjOwnerItemProperty, value);
    }

    private ToolStripDropDownCloseReason menmCloseReason
    {
      get => this.GetValue<ToolStripDropDownCloseReason>(ToolStripDropDown.menmCloseReasonProperty);
      set => this.SetValue<ToolStripDropDownCloseReason>(ToolStripDropDown.menmCloseReasonProperty, value);
    }

    private Component mobjSourceComponent
    {
      get => this.GetValue<Component>(ToolStripDropDown.mobjSourceComponentProperty, (Component) null);
      set => this.SetValue<Component>(ToolStripDropDown.mobjSourceComponentProperty, value);
    }

    private IIdentifiedComponent mobjSourceMemberComponent
    {
      get => this.GetValue<IIdentifiedComponent>(ToolStripDropDown.mobjSourceMemberComponentProperty, (IIdentifiedComponent) null);
      set => this.SetValue<IIdentifiedComponent>(ToolStripDropDown.mobjSourceMemberComponentProperty, value);
    }

    private ToolStripDropDown.ToolStripDropDownForm mobjToolStripDropDownForm
    {
      get => this.GetValue<ToolStripDropDown.ToolStripDropDownForm>(ToolStripDropDown.mobjToolStripDropDownFormProperty, (ToolStripDropDown.ToolStripDropDownForm) null);
      set => this.SetValue<ToolStripDropDown.ToolStripDropDownForm>(ToolStripDropDown.mobjToolStripDropDownFormProperty, value);
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>true to enable item reordering; otherwise, false.</returns>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new bool AllowItemReorder
    {
      get => base.AllowItemReorder;
      set => base.AllowItemReorder = value;
    }

    /// <summary>
    /// Gets or sets a value indicating whether the <see cref="P:Gizmox.WebGUI.Forms.ToolStripDropDown.Opacity"></see> of the form can be adjusted.
    /// </summary>
    /// <value><c>true</c> if [allow transparency]; otherwise, <c>false</c>.</value>
    /// <returns>true if the <see cref="P:Gizmox.WebGUI.Forms.ToolStripDropDown.Opacity"></see> of the form can be adjusted; otherwise, false. </returns>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public bool AllowTransparency
    {
      get => false;
      set
      {
      }
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>One of the <see cref="T:Gizmox.WebGUI.Forms.AnchorStyles"></see> values.</returns>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override AnchorStyles Anchor
    {
      get => base.Anchor;
      set => base.Anchor = value;
    }

    /// <summary>
    /// Gets or sets a value indicating whether the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control should automatically close when it has lost activation.
    /// </summary>
    /// <value><c>true</c> if [auto close]; otherwise, <c>false</c>.</value>
    /// <returns>true if the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control automatically closes; otherwise, false. The default is true.</returns>
    /// <PermissionSet>
    /// 	<IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    /// 	<IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    [DefaultValue(true)]
    [SRDescription("ToolStripDropDownAutoCloseDescr")]
    [SRCategory("CatBehavior")]
    public bool AutoClose
    {
      get => this.mblnAutoClose;
      set
      {
        if (this.mblnAutoClose == value)
          return;
        this.mblnAutoClose = value;
        if (this.mobjToolStripDropDownForm == null)
          return;
        this.mobjToolStripDropDownForm.Update();
      }
    }

    /// <summary>
    /// Gets or sets a value indicating whether the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> automatically adjusts its size when the form is resized.
    /// </summary>
    /// <value></value>
    /// <returns>true if the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> control automatically resizes; otherwise, false. The default is true.</returns>
    /// <PermissionSet>
    /// 	<IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    /// 	<IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    [DefaultValue(true)]
    public override bool AutoSize
    {
      get => this.mblnAutoSize;
      set
      {
        if (this.mblnAutoSize == value)
          return;
        this.mblnAutoSize = value;
        this.OnAutoSizeChanged(EventArgs.Empty);
      }
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>A <see cref="T:Gizmox.WebGUI.Forms.ContextMenu"></see>.</returns>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    public new ContextMenu ContextMenu
    {
      get => base.ContextMenu;
      set => base.ContextMenu = value;
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>A <see cref="T:Gizmox.WebGUI.Forms.ContextMenuStrip"></see>.</returns>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new ContextMenuStrip ContextMenuStrip
    {
      get => base.ContextMenuStrip;
      set => base.ContextMenuStrip = value;
    }

    protected override DockStyle DefaultDock => DockStyle.None;

    protected override bool DefaultShowItemToolTips => true;

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>One of the <see cref="T:Gizmox.WebGUI.Forms.DockStyle"></see> values.</returns>
    [DefaultValue(DockStyle.None)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    [Browsable(false)]
    public override DockStyle Dock
    {
      get => base.Dock;
      set => base.Dock = value;
    }

    /// <summary>
    /// Gets or sets a value indicating whether a three-dimensional shadow effect appears when the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is displayed.
    /// </summary>
    /// <value><c>true</c> if [drop shadow enabled]; otherwise, <c>false</c>.</value>
    /// <returns>true to enable the shadow effect; otherwise, false.</returns>
    /// <PermissionSet>
    /// 	<IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    /// 	<IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public bool DropShadowEnabled
    {
      get => false;
      set
      {
      }
    }

    /// <summary>
    /// Gets or sets the font of the text displayed on the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see>.
    /// </summary>
    /// <value></value>
    /// <returns>The <see cref="T:System.Drawing.Font"></see> to apply to the text displayed by the control.</returns>
    public override Font Font
    {
      get => this.IsAutoGenerated && this.OwnerItem != null ? this.OwnerItem.Font : base.Font;
      set => base.Font = value;
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <returns>One of <see cref="T:Gizmox.WebGUI.Forms.ToolStripGripDisplayStyle"></see> the values.</returns>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    public new ToolStripGripDisplayStyle GripDisplayStyle => base.GripDisplayStyle;

    /// <summary>This property is not relevant to this class.</summary>
    /// <returns>A <see cref="T:Gizmox.WebGUI.Forms.Padding"></see> value.</returns>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [Browsable(false)]
    public new Padding GripMargin
    {
      get => base.GripMargin;
      set => base.GripMargin = value;
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>One of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripGripStyle"></see> values.</returns>
    /// <PermissionSet>
    /// 	<IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    /// 	<IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [DefaultValue(ToolStripGripStyle.Hidden)]
    [Browsable(false)]
    public new ToolStripGripStyle GripStyle
    {
      get => base.GripStyle;
      set => base.GripStyle = value;
    }

    /// <summary>
    /// Gets a value indicating whether this <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> was automatically generated.
    /// </summary>
    /// <value>
    /// 	<c>true</c> if this instance is auto generated; otherwise, <c>false</c>.
    /// </value>
    /// <returns>true if this <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is generated automatically; otherwise, false.</returns>
    [Browsable(false)]
    public bool IsAutoGenerated => this.mblnIsAutoGenerated;

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>A <see cref="T:System.Drawing.Point"></see>.</returns>
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new Point Location
    {
      get => base.Location;
      set => base.Location = value;
    }

    /// <summary>Determines the opacity of the form.</summary>
    /// <value>The opacity.</value>
    /// <returns>The level of opacity for the form. The default is 1.00.</returns>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public double Opacity
    {
      get => 1.0;
      set
      {
      }
    }

    /// <summary>
    /// Gets or sets the <see cref="T:Gizmox.WebGUI.Forms.ToolStripItem"></see> that is the owner of this <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see>.
    /// </summary>
    /// <value>The owner item.</value>
    /// <returns>The <see cref="T:Gizmox.WebGUI.Forms.ToolStripItem"></see> that is the owner of this <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see>. The default value is null.</returns>
    [Browsable(false)]
    [DefaultValue(null)]
    public ToolStripItem OwnerItem
    {
      get => this.mobjOwnerItem;
      set
      {
        if (this.mobjOwnerItem == value)
          return;
        Font font = this.Font;
        int rightToLeft = (int) this.RightToLeft;
        this.mobjOwnerItem = value;
      }
    }

    /// <summary>Gets the parent of this component.</summary>
    public override Component InternalParent
    {
      get => base.InternalParent ?? (Component) this.mobjOwnerItem;
      set => base.InternalParent = value;
    }

    /// <summary>Gets or sets the source component internal.</summary>
    /// <value>The source component internal.</value>
    internal Component SourceComponentInternal
    {
      get => this.mobjSourceComponent;
      set
      {
        if (value == this.mobjSourceComponent)
          return;
        this.mobjSourceComponent = value;
      }
    }

    internal IIdentifiedComponent SourceMemberComponentInternal
    {
      get => this.mobjSourceMemberComponent;
      set
      {
        if (value == this.mobjSourceMemberComponent)
          return;
        this.mobjSourceMemberComponent = value;
      }
    }

    /// <summary>
    /// Gets or sets the window region associated with the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see>.
    /// </summary>
    /// <value>The region.</value>
    /// <returns>The window <see cref="T:System.Drawing.Region"></see> associated with the control.</returns>
    [Obsolete("Not implemented. Added for migration compatibility")]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public Region Region
    {
      get => (Region) null;
      set
      {
      }
    }

    /// <summary>
    /// Gets a value indicating whether [right to left inherited].
    /// </summary>
    /// <value>
    /// 	<c>true</c> if [right to left inherited]; otherwise, <c>false</c>.
    /// </value>
    private bool RightToLeftInherited => !this.ShouldSerializeRightToLeft();

    /// <summary>
    /// Gets or sets a value indicating whether control's elements are aligned to support locales using right-to-left fonts.
    /// </summary>
    /// <value></value>
    /// <returns>One of the <see cref="T:Gizmox.WebGUI.Forms.RightToLeft"></see> values. The default is <see cref="F:Gizmox.WebGUI.Forms.RightToLeft.Inherit"></see>.</returns>
    /// <exception cref="T:System.ComponentModel.InvalidEnumArgumentException">The assigned value is not one of the <see cref="T:Gizmox.WebGUI.Forms.RightToLeft"></see> values. </exception>
    /// <PermissionSet><IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" /><IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" /><IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" /><IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" /></PermissionSet>
    [SRCategory("CatAppearance")]
    [Localizable(true)]
    [AmbientValue(2)]
    [SRDescription("ControlRightToLeftDescr")]
    public override RightToLeft RightToLeft
    {
      get => this.RightToLeftInherited && this.OwnerItem != null ? this.OwnerItem.RightToLeft : base.RightToLeft;
      set => base.RightToLeft = value;
    }

    /// <summary>Gets the drop down form.</summary>
    /// <value>The drop down form.</value>
    internal Form DropDownForm => (Form) this.mobjToolStripDropDownForm;

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>true to enable stretching; otherwise, false.</returns>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    public new bool Stretch
    {
      get => base.Stretch;
      set => base.Stretch = value;
    }

    /// <summary>This property is not relevant to this class.</summary>
    /// <value></value>
    /// <returns>An <see cref="T:System.Int32"></see>.</returns>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public new int TabIndex
    {
      get => base.TabIndex;
      set => base.TabIndex = value;
    }

    /// <summary>
    /// Specifies the direction in which to draw the text on the item.
    /// </summary>
    /// <value></value>
    /// <returns>One of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripTextDirection"></see> values. The default is <see cref="F:Gizmox.WebGUI.Forms.ToolStripTextDirection.Horizontal"></see>.</returns>
    [DefaultValue(ToolStripTextDirection.Horizontal)]
    [SRCategory("CatAppearance")]
    [Browsable(false)]
    [SRDescription("ToolStripTextDirectionDescr")]
    public override ToolStripTextDirection TextDirection
    {
      get => base.TextDirection;
      set => base.TextDirection = value;
    }

    /// <summary>
    /// Gets or sets a value indicating whether the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is a top-level control.
    /// </summary>
    /// <value><c>true</c> if [top level]; otherwise, <c>false</c>.</value>
    /// <returns>true if the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is a top-level control; otherwise, false.</returns>
    /// <PermissionSet>
    /// 	<IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// 	<IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    /// 	<IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [Browsable(false)]
    public bool TopLevel
    {
      get => this.GetTopLevel();
      set
      {
        if (value == this.GetTopLevel())
          return;
        this.SetTopLevelInternal(value);
      }
    }

    /// <summary>
    /// Gets the <see cref="T:Gizmox.WebGUI.Forms.ToolStripItem"></see> that is the overflow button for a <see cref="T:Gizmox.WebGUI.Forms.ToolStrip"></see> with overflow enabled.
    /// </summary>
    /// <returns>An object of type <see cref="T:Gizmox.WebGUI.Forms.ToolStripOverflowButton"></see> with its <see cref="T:Gizmox.WebGUI.Forms.ToolStripItemAlignment"></see> set to <see cref="F:Gizmox.WebGUI.Forms.ToolStripItemAlignment.Right"></see> and its <see cref="T:Gizmox.WebGUI.Forms.ToolStripItemOverflow"></see> value set to <see cref="F:Gizmox.WebGUI.Forms.ToolStripItemOverflow.Never"></see>.</returns>
    /// <PermissionSet>
    /// <IPermission class="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// <IPermission class="System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// <IPermission class="System.Security.Permissions.SecurityPermission, mscorlib, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Flags="UnmanagedCode, ControlEvidence" />
    /// <IPermission class="System.Diagnostics.PerformanceCounterPermission, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" version="1" Unrestricted="true" />
    /// </PermissionSet>
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public new ToolStripOverflowButton OverflowButton => base.OverflowButton;

    /// <summary>
    /// Gets or sets a value indicating whether the form should be displayed as a topmost form.
    /// </summary>
    /// <value><c>true</c> if [top most]; otherwise, <c>false</c>.</value>
    /// <returns>true in all cases.</returns>
    protected virtual bool TopMost => true;

    /// <summary>
    /// Gets or sets a value indicating whether the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is visible or hidden.
    /// </summary>
    /// <value></value>
    /// <returns>true if the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown"></see> is visible; otherwise, false. The default is false.</returns>
    [Browsable(false)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public new bool Visible => this.DropDownForm != null && this.DropDownForm.Visible;

    /// <summary>Gets the header panel.</summary>
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    [Browsable(false)]
    [SRDescription("ToolStripDropDownHeaderPanelDescr")]
    [SRCategory("CatAppearance")]
    public ToolStripDropDown.ToolStripDropDownHeaderPanel HeaderPanel
    {
      get
      {
        ToolStripDropDown.ToolStripDropDownHeaderPanel objValue = this.GetValue<ToolStripDropDown.ToolStripDropDownHeaderPanel>(ToolStripDropDown.HeaderPanelProperty);
        if (objValue == null)
        {
          objValue = new ToolStripDropDown.ToolStripDropDownHeaderPanel();
          this.SetValue<ToolStripDropDown.ToolStripDropDownHeaderPanel>(ToolStripDropDown.HeaderPanelProperty, objValue);
        }
        return objValue;
      }
    }

    /// <summary>
    /// 
    /// </summary>
    [ToolboxItem(false)]
    [Serializable]
    public class ToolStripDropDownHeaderPanel : Panel
    {
      /// <summary>
      /// Initializes a new instance of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown.ToolStripDropDownHeaderPanel" /> class.
      /// </summary>
      public ToolStripDropDownHeaderPanel()
      {
        this.Size = Size.Empty;
        this.Dock = DockStyle.Left;
      }

      /// <summary>Gets/Sets the controls docking style</summary>
      public override DockStyle Dock
      {
        get => base.Dock;
        set => base.Dock = value != DockStyle.None && value != DockStyle.Fill ? value : throw new ArgumentException(string.Format("Invalid docking value '{0}' for a tool strip drop down header panel."));
      }
    }

    /// <summary>
    /// 
    /// </summary>
    [ToolboxItem(false)]
    [Serializable]
    private class ToolStripDropDownContentPanel : Panel
    {
      private ToolStripDropDown mobjOwnerToolStripDropDown;

      /// <summary>
      /// Initializes a new instance of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown.ToolStripDropDownContentPanel" /> class.
      /// </summary>
      /// <param name="objOwnerToolStripDropDown">The obj owner tool strip drop down.</param>
      public ToolStripDropDownContentPanel()
      {
        this.AutoScroll = true;
        this.ScrollerType = ScrollerType.Arrows;
        this.VScroll = true;
      }

      /// <summary>Gets or sets the control custom style.</summary>
      public override string CustomStyle
      {
        get => nameof (ToolStripDropDownContentPanel);
        set => base.CustomStyle = value;
      }

      /// <summary>Gets or sets the owner tool strip drop down.</summary>
      /// <value>The owner tool strip drop down.</value>
      internal ToolStripDropDown OwnerToolStripDropDown
      {
        get => this.mobjOwnerToolStripDropDown;
        set => this.mobjOwnerToolStripDropDown = value;
      }

      /// <summary>Renders the controls sub tree</summary>
      /// <param name="objContext"></param>
      /// <param name="objWriter"></param>
      /// <param name="lngRequestID"></param>
      protected override void RenderControls(
        IContext objContext,
        IResponseWriter objWriter,
        long lngRequestID)
      {
        if (this.mobjOwnerToolStripDropDown == null)
          return;
        ToolStripItemCollection items = this.mobjOwnerToolStripDropDown.Items;
        if (items == null)
          return;
        foreach (ToolStripItem toolStripItem in (ArrangedElementCollection) items)
        {
          if (toolStripItem.Visible)
            toolStripItem.RenderToolStripItem(objContext, objWriter, lngRequestID);
        }
      }

      /// <summary>Get maximum width of image over all items</summary>
      /// <returns></returns>
      internal int GetContentImageMaxWidth()
      {
        int contentImageMaxWidth = 0;
        if (this.mobjOwnerToolStripDropDown != null)
        {
          Size size = this.mobjOwnerToolStripDropDown.ImageScalingSize;
          contentImageMaxWidth = size.Width;
          ToolStripItemCollection items = this.mobjOwnerToolStripDropDown.Items;
          if (items != null)
          {
            contentImageMaxWidth = 0;
            foreach (ToolStripItem toolStripItem in (ArrangedElementCollection) items)
            {
              if (toolStripItem.Visible)
              {
                int width;
                if (!toolStripItem.AutoSize)
                {
                  size = this.mobjOwnerToolStripDropDown.ImageScalingSize;
                  width = size.Width;
                }
                else
                {
                  size = toolStripItem.GetPreferredSizeByImage(Size.Empty);
                  width = size.Width;
                }
                int num = width;
                if (num > contentImageMaxWidth)
                  contentImageMaxWidth = num;
              }
            }
          }
        }
        return contentImageMaxWidth;
      }

      /// <summary>Gets the size of the content preffered.</summary>
      /// <returns></returns>
      internal Size GetContentPrefferedSize()
      {
        int width = 0;
        int height = 0;
        ToolStripMenuItemSkin skin = SkinFactory.GetSkin((ISkinable) this, typeof (ToolStripMenuItemSkin)) as ToolStripMenuItemSkin;
        if (this.mobjOwnerToolStripDropDown != null)
        {
          ToolStripItemCollection items = this.mobjOwnerToolStripDropDown.Items;
          if (items != null)
          {
            int num1 = 0;
            foreach (ToolStripItem toolStripItem in (ArrangedElementCollection) items)
            {
              if (toolStripItem.Visible)
              {
                Size size = toolStripItem.AutoSize ? toolStripItem.GetPreferredSize(Size.Empty) : toolStripItem.Size;
                if (size.Width > num1)
                  num1 = size.Width;
                height += size.Height;
              }
            }
            width += num1;
            if (skin != null)
            {
              int num2 = this.Context == null ? 0 : (this.Context.RightToLeft ? 1 : 0);
              int num3 = (num2 == 0 ? width + skin.MenuItemImageWidthLTR : width + skin.MenuItemImageWidthRTL) + skin.TextImageGapSize + skin.TextArrowGapSize;
              width = num2 == 0 ? num3 + skin.MenuItemArrowImageWidthLTR : num3 + skin.MenuItemArrowImageWidthRTL;
            }
          }
        }
        if (skin != null)
          width += skin.MenuItemImageExtraWidth;
        return new Size(width, height);
      }
    }

    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    protected internal class ToolStripDropDownForm : Form
    {
      private static readonly SerializableProperty mobjOwnerToolStripDropDownProperty = SerializableProperty.Register(nameof (mobjOwnerToolStripDropDown), typeof (ToolStripDropDown), typeof (ToolStripDropDown.ToolStripDropDownForm));
      private static readonly SerializableProperty mobjOwnerToolStripItemProperty = SerializableProperty.Register(nameof (mobjOwnerToolStripItem), typeof (ToolStripItem), typeof (ToolStripDropDown.ToolStripDropDownForm));
      private ToolStripDropDown.ToolStripDropDownContentPanel mobjToolStripDropDownContentPanel;

      /// <summary>Gets the owner tool strip item.</summary>
      /// <value>The owner tool strip item.</value>
      private ToolStripItem OwnerToolStripItem
      {
        get
        {
          if (this.mobjOwnerToolStripItem == null && this.mobjOwnerToolStripDropDown != null)
            this.mobjOwnerToolStripItem = this.mobjOwnerToolStripDropDown.OwnerItem;
          return this.mobjOwnerToolStripItem;
        }
      }

      /// <summary>
      /// Initializes a new instance of the <see cref="T:Gizmox.WebGUI.Forms.ToolStripDropDown.ToolStripDropDownForm" /> class.
      /// </summary>
      /// <param name="objOwnerToolStripDropDown">The obj owner tool strip drop down.</param>
      public ToolStripDropDownForm(ToolStripDropDown objOwnerToolStripDropDown)
      {
        this.InitializeComponent();
        this.mobjToolStripDropDownContentPanel.OwnerToolStripDropDown = this.mobjOwnerToolStripDropDown = objOwnerToolStripDropDown;
        if (this.mobjOwnerToolStripDropDown != null)
        {
          this.Controls.Add((Control) this.mobjOwnerToolStripDropDown.HeaderPanel);
          this.mobjOwnerToolStripDropDown.ItemAdded += new ToolStripItemEventHandler(this.OnOwnerDropDownItemCollectionChanged);
          this.mobjOwnerToolStripDropDown.ItemRemoved += new ToolStripItemEventHandler(this.OnOwnerDropDownItemCollectionChanged);
          this.Font = objOwnerToolStripDropDown.Font;
          this.BackColor = objOwnerToolStripDropDown.BackColor;
          this.ForeColor = objOwnerToolStripDropDown.ForeColor;
        }
        if (this.OwnerToolStripItem == null || this.OwnerToolStripItem.Parent == null)
          return;
        this.Theme = this.OwnerToolStripItem.Parent.Theme;
      }

      /// <summary>
      /// Required method for Designer support - do not modify
      /// the contents of this method with the code editor.
      /// </summary>
      private void InitializeComponent()
      {
        this.mobjToolStripDropDownContentPanel = new ToolStripDropDown.ToolStripDropDownContentPanel();
        this.SuspendLayout();
        this.mobjToolStripDropDownContentPanel.Dock = DockStyle.Fill;
        this.mobjToolStripDropDownContentPanel.Location = new Point(100, 0);
        this.mobjToolStripDropDownContentPanel.Name = "mobjToolStripDropDownContentPanel";
        this.mobjToolStripDropDownContentPanel.Size = new Size(577, 506);
        this.mobjToolStripDropDownContentPanel.TabIndex = 1;
        this.Controls.Add((Control) this.mobjToolStripDropDownContentPanel);
        this.FormBorderStyle = FormBorderStyle.Sizable;
        this.Size = new Size(677, 506);
        this.CustomStyle = nameof (ToolStripDropDown);
        this.MinimumSize = new Size(80, 0);
        this.Text = "Form1";
        this.ResumeLayout(false);
      }

      /// <summary>
      /// Called when [owner drop down item collection changed].
      /// </summary>
      /// <param name="objSender">The obj sender.</param>
      /// <param name="objArgs">The <see cref="T:Gizmox.WebGUI.Forms.ToolStripItemEventArgs" /> instance containing the event data.</param>
      private void OnOwnerDropDownItemCollectionChanged(
        object objSender,
        ToolStripItemEventArgs objArgs)
      {
        this.InitializePrefferedSize();
      }

      /// <summary>
      /// Raises the <see cref="E:Gizmox.WebGUI.Forms.Form.Load"></see> event.
      /// </summary>
      /// <param name="e">An <see cref="T:System.EventArgs"></see> that contains the event data.</param>
      protected override void OnLoad(EventArgs e)
      {
        base.OnLoad(e);
        this.InitializePrefferedSize();
      }

      /// <summary>Initializes a preffered size.</summary>
      private void InitializePrefferedSize()
      {
        int width = 0;
        int height = 0;
        if (SkinFactory.GetSkin((ISkinable) this, typeof (ToolStripDropDownSkin)) is ToolStripDropDownSkin skin)
        {
          height += skin.DropDownOffsetHeight;
          width += skin.DropDownOffsetWidth;
        }
        if (this.mobjToolStripDropDownContentPanel != null)
        {
          Size contentPrefferedSize = this.mobjToolStripDropDownContentPanel.GetContentPrefferedSize();
          width += contentPrefferedSize.Width;
          height += contentPrefferedSize.Height;
        }
        if (this.mobjOwnerToolStripDropDown != null && this.mobjOwnerToolStripDropDown.HeaderPanel != null)
        {
          switch (this.mobjOwnerToolStripDropDown.HeaderPanel.Dock)
          {
            case DockStyle.Top:
            case DockStyle.Bottom:
              height += this.mobjOwnerToolStripDropDown.HeaderPanel.Height;
              break;
            case DockStyle.Right:
            case DockStyle.Left:
              width += this.mobjOwnerToolStripDropDown.HeaderPanel.Width;
              break;
          }
        }
        if (height <= 0 || width <= 0)
          return;
        this.Size = new Size(width, height);
      }

      /// <summary>Renders the image size attributes.</summary>
      /// <param name="objWriter">The writer.</param>
      /// 
      ///             /// <param name="blnForceRender">if set to <c>true</c> [BLN force render].</param>
      private void RenderImageSizeAttributes(IAttributeWriter objWriter)
      {
        if (this.mobjOwnerToolStripDropDown == null)
          return;
        Size imageScalingSize = this.mobjOwnerToolStripDropDown.ImageScalingSize;
        objWriter.WriteAttributeString("IH", imageScalingSize.Height.ToString((IFormatProvider) CultureInfo.InvariantCulture));
        objWriter.WriteAttributeString("IW", imageScalingSize.Width.ToString((IFormatProvider) CultureInfo.InvariantCulture));
        objWriter.WriteAttributeString("MIMW", this.mobjToolStripDropDownContentPanel.GetContentImageMaxWidth().ToString((IFormatProvider) CultureInfo.InvariantCulture));
      }

      /// <summary>Renders the forms attribute</summary>
      /// <param name="objContext"></param>
      /// <param name="objWriter"></param>
      protected override void RenderAttributes(IContext objContext, IAttributeWriter objWriter)
      {
        base.RenderAttributes(objContext, objWriter);
        this.RenderImageSizeAttributes(objWriter);
        ToolStripItem ownerToolStripItem = this.OwnerToolStripItem;
        if (ownerToolStripItem != null)
        {
          IAttributeWriter attributeWriter = objWriter;
          long num = ownerToolStripItem.OwnerID;
          string str1 = num.ToString();
          num = ownerToolStripItem.MemberID;
          string str2 = num.ToString();
          string strValue = string.Format("{0}_{1}", (object) str1, (object) str2);
          attributeWriter.WriteAttributeString("oId", strValue);
          if (ownerToolStripItem.Owner is ToolStripDropDown && ownerToolStripItem is ToolStripDropDownItem stripDropDownItem && stripDropDownItem.DropDown.Items.Count > 0)
            objWriter.WriteAttributeString("SF", "1");
        }
        objWriter.WriteAttributeString("TSDD", "1");
        if (this.mobjOwnerToolStripDropDown.AutoClose)
          return;
        objWriter.WriteAttributeString("ACDD", "0");
      }

      /// <summary>Fires an event.</summary>
      /// <param name="objEvent">event.</param>
      protected override void FireEvent(IEvent objEvent)
      {
        ToolStripItem toolStripItem = (ToolStripItem) null;
        if (this.mobjOwnerToolStripDropDown != null)
        {
          string member = objEvent.Member;
          if (!string.IsNullOrEmpty(member))
          {
            int result = -1;
            if (int.TryParse(member, out result))
              toolStripItem = this.mobjOwnerToolStripDropDown.Items[result - 1];
          }
        }
        if (toolStripItem != null)
          toolStripItem.FireToolStripItemEvent(objEvent);
        else
          base.FireEvent(objEvent);
      }

      private ToolStripDropDown mobjOwnerToolStripDropDown
      {
        get => this.GetValue<ToolStripDropDown>(ToolStripDropDown.ToolStripDropDownForm.mobjOwnerToolStripDropDownProperty, (ToolStripDropDown) null);
        set => this.SetValue<ToolStripDropDown>(ToolStripDropDown.ToolStripDropDownForm.mobjOwnerToolStripDropDownProperty, value);
      }

      private ToolStripItem mobjOwnerToolStripItem
      {
        get => this.GetValue<ToolStripItem>(ToolStripDropDown.ToolStripDropDownForm.mobjOwnerToolStripItemProperty, (ToolStripItem) null);
        set => this.SetValue<ToolStripItem>(ToolStripDropDown.ToolStripDropDownForm.mobjOwnerToolStripItemProperty, value);
      }
    }
  }
}
